### ISSUE TITLE
CUIからサンプルを動作させる

### ISSUE THREAD

**Issue by MtBlue81** [MtBlue81/swagger-to-normalizr#7]
スタブサーバをきちんと組んでパターンが見えるようにする

**Comment by MtBlue81** [comment]
Nodeでのfetch周りが動かないので諦める
```
ReferenceError: fetch is not defined
    at a [as http] (/Users/aoyama/workspace/swagger-to-normalizr/examples/bundle.node.js:17417:3935)
    at Function.a [as execute] (/Users/aoyama/workspace/swagger-to-normalizr/examples/bundle.node.js:17417:14226)
    at a.execute (/Users/aoyama/workspace/swagger-to-normalizr/examples/bundle.node.js:17417:13036)
    at /Users/aoyama/workspace/swagger-to-normalizr/examples/bundle.node.js:17417:27296
    at Object.action [as dispatch] (/Users/aoyama/workspace/swagger-to-normalizr/examples/bundle.node.js:17389:14)
    at dispatch (/Users/aoyama/workspace/swagger-to-normalizr/examples/bundle.node.js:13299:13)
    at getPets (/Users/aoyama/workspace/swagger-to-normalizr/examples/bundle.node.js:13295:7)
    at __webpack_require__.then.middleware (/Users/aoyama/workspace/swagger-to-normalizr/examples/bundle.node.js:13302:5)
    at <anonymous>

```
